FROM python:3.12

RUN pip install poetry

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*
    
WORKDIR /quizApp
    
COPY . /quizApp/

RUN poetry config virtualenvs.create false
RUN poetry install

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "quizbackend.routes.adminRoute:app","--host", "0.0.0.0", "--port", "8000", "--reload"]